/**
 * @file main.c
 * @brief ESP32-C3 贪吃蛇游戏主程序
 * @author Generated by AI
 * @date 2026-05-29
 * 
 * 硬件配置：
 * - ST7789 240x240 SPI显示屏
 *   - MOSI=5, CLK=18, DC=6, CS=4, RST=-1
 * - ADC按键：IO3（12位ADC）
 * - 数字按键：IO9（上拉输入，返回键）
 * - LED指示灯：IO19（高电平点亮）
 */

#include <stdio.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "driver/adc.h"
#include "driver/gpio.h"
#include "esp_log.h"
#include "st7789.h"
#include "snake_game.h"

/* 测试模式开关 - 设置为1运行屏幕测试 */
#define RUN_DISPLAY_TEST 0

/* 日志标签 */
static const char *TAG = "Main";

/* 按键配置 */
#define ADC_KEY_PIN    3
#define DIGITAL_KEY_PIN 9
#define LED_PIN        19

/* 游戏速度（毫秒） */
#define GAME_SPEED_MS  200

/* 按键去抖时间（毫秒） */
#define DEBOUNCE_MS    100

/* 全局变量 */
static uint32_t last_adc_time = 0;
static uint32_t last_digital_time = 0;
static Direction_t last_dir = DIR_NONE;

/**
 * @brief 初始化ADC
 */
static void adc_init(void)
{
    // 配置ADC通道
    adc1_config_width(ADC_WIDTH_BIT_12);
    adc1_config_channel_atten(ADC1_CHANNEL_3, ADC_ATTEN_DB_11);
}

/**
 * @brief 读取ADC按键值
 */
static int read_adc_key(void)
{
    return adc1_get_raw(ADC1_CHANNEL_3);
}

/**
 * @brief 初始化数字按键
 */
static void digital_key_init(void)
{
    gpio_config_t io_conf = {
        .pin_bit_mask = (1ULL << DIGITAL_KEY_PIN),
        .mode = GPIO_MODE_INPUT,
        .pull_up_en = GPIO_PULLUP_ENABLE,
        .pull_down_en = GPIO_PULLDOWN_DISABLE,
        .intr_type = GPIO_INTR_DISABLE
    };
    gpio_config(&io_conf);
}

/**
 * @brief 读取数字按键状态
 */
static bool read_digital_key(void)
{
    return gpio_get_level(DIGITAL_KEY_PIN) == 0;
}

/**
 * @brief 初始化LED
 */
static void led_init(void)
{
    gpio_config_t io_conf = {
        .pin_bit_mask = (1ULL << LED_PIN),
        .mode = GPIO_MODE_OUTPUT,
        .pull_up_en = GPIO_PULLUP_DISABLE,
        .pull_down_en = GPIO_PULLDOWN_DISABLE,
        .intr_type = GPIO_INTR_DISABLE
    };
    gpio_config(&io_conf);

    // 默认关闭LED
    gpio_set_level(LED_PIN, 0);
}

/**
 * @brief 设置LED状态
 */
static void led_set(bool on)
{
    gpio_set_level(LED_PIN, on ? 1 : 0);
}

/**
 * @brief 根据ADC值获取按键功能
 */
static Direction_t get_direction_from_adc(int adc_value)
{
    if (adc_value < ADC_THRESHOLD_DOWN) {
        return DIR_DOWN;
    } else if (adc_value < ADC_THRESHOLD_LEFT) {
        return DIR_LEFT;
    } else if (adc_value < ADC_THRESHOLD_RIGHT) {
        return DIR_RIGHT;
    } else if (adc_value < ADC_THRESHOLD_UP) {
        return DIR_UP;
    } else if (adc_value < ADC_THRESHOLD_CONFIRM) {
        return DIR_NONE;  // 确认键单独处理
    } else {
        return DIR_NONE;
    }
}

/**
 * @brief 按键处理任务
 */
static void key_task(void *pvParameters)
{
    int adc_value;
    Direction_t dir;
    uint32_t current_time;
    bool digital_pressed = false;

    while (1) {
        current_time = xTaskGetTickCount() * portTICK_PERIOD_MS;

        // 处理ADC按键
        if (current_time - last_adc_time >= DEBOUNCE_MS) {
            adc_value = read_adc_key();
            last_adc_time = current_time;
            
            // 输出ADC值用于调试
            ESP_LOGI(TAG, "ADC Value: %d", adc_value);

            // 检测确认键
            if (adc_value >= ADC_THRESHOLD_UP && adc_value < ADC_THRESHOLD_CONFIRM) {
                GameState_t state = game_get_state();
                
                if (state == GAME_IDLE) {
                    // 开始游戏
                    game_start();
                    led_set(true);
                } else if (state == GAME_PLAYING || state == GAME_PAUSED) {
                    // 暂停/继续
                    game_toggle_pause();
                } else if (state == GAME_OVER) {
                    // 重新开始
                    game_start();
                    led_set(true);
                }
                
                // 按键反馈
                led_set(true);
                vTaskDelay(100 / portTICK_PERIOD_MS);
                if (game_get_state() == GAME_PLAYING) {
                    led_set(true);
                } else {
                    led_set(false);
                }
            } else {
                // 方向键处理
                dir = get_direction_from_adc(adc_value);
                if (dir != DIR_NONE && dir != last_dir) {
                    game_change_dir(dir);
                    last_dir = dir;
                    // 按键反馈
                    led_set(true);
                    vTaskDelay(50 / portTICK_PERIOD_MS);
                    if (game_get_state() == GAME_PLAYING) {
                        led_set(true);
                    } else {
                        led_set(false);
                    }
                } else if (dir == DIR_NONE) {
                    last_dir = DIR_NONE;
                }
            }
        }

        // 处理数字按键（IO9）
        if (current_time - last_digital_time >= DEBOUNCE_MS) {
            if (read_digital_key() && !digital_pressed) {
                digital_pressed = true;
                last_digital_time = current_time;

                // 退出/重置游戏
                game_reset();
                led_set(false);

                ESP_LOGI(TAG, "Digital key pressed, resetting game");
            } else if (!read_digital_key()) {
                digital_pressed = false;
            }
        }

        vTaskDelay(10 / portTICK_PERIOD_MS);
    }
}

/**
 * @brief 游戏主循环任务
 */
static void game_task(void *pvParameters)
{
    while (1) {
        game_update();
        vTaskDelay(GAME_SPEED_MS / portTICK_PERIOD_MS);
    }
}

void app_main(void)
{
    ESP_LOGI(TAG, "Starting Snake Game on ESP32-C3");

#if RUN_DISPLAY_TEST
    /* 运行屏幕测试 */
    ESP_LOGI(TAG, "Running display test mode...");
    st7789_init();
    
    // 测试1: 全屏填充红色
    ESP_LOGI(TAG, "Test 1: RED");
    st7789_fill_rect(0, 0, SCREEN_WIDTH - 1, SCREEN_HEIGHT - 1, COLOR_RED);
    vTaskDelay(2000 / portTICK_PERIOD_MS);
    
    // 测试2: 全屏填充绿色
    ESP_LOGI(TAG, "Test 2: GREEN");
    st7789_fill_rect(0, 0, SCREEN_WIDTH - 1, SCREEN_HEIGHT - 1, COLOR_GREEN);
    vTaskDelay(2000 / portTICK_PERIOD_MS);
    
    // 测试3: 全屏填充蓝色
    ESP_LOGI(TAG, "Test 3: BLUE");
    st7789_fill_rect(0, 0, SCREEN_WIDTH - 1, SCREEN_HEIGHT - 1, COLOR_BLUE);
    vTaskDelay(2000 / portTICK_PERIOD_MS);
    
    // 测试4: 显示文本
    ESP_LOGI(TAG, "Test 4: TEXT");
    st7789_fill_rect(0, 0, SCREEN_WIDTH - 1, SCREEN_HEIGHT - 1, COLOR_BLACK);
    st7789_draw_string(40, 60, "ST7789 TEST", COLOR_WHITE, COLOR_BLACK);
    st7789_draw_string(50, 100, "DISPLAY OK!", COLOR_GREEN, COLOR_BLACK);
    st7789_draw_string(30, 140, "ESP32-C3 Snake Game", COLOR_YELLOW, COLOR_BLACK);
    vTaskDelay(2000 / portTICK_PERIOD_MS);
    
    // 测试5: 绘制直线
    ESP_LOGI(TAG, "Test 5: LINES");
    st7789_fill_rect(0, 0, SCREEN_WIDTH - 1, SCREEN_HEIGHT - 1, COLOR_BLACK);
    st7789_draw_line(10, 10, 230, 10, COLOR_RED);      // 水平线
    st7789_draw_line(10, 10, 10, 230, COLOR_GREEN);    // 垂直线
    st7789_draw_line(10, 230, 230, 230, COLOR_BLUE);   // 底部水平线
    st7789_draw_line(230, 10, 230, 230, COLOR_YELLOW); // 右侧垂直线
    st7789_draw_line(10, 10, 230, 230, COLOR_ORANGE);  // 对角线
    st7789_draw_line(230, 10, 10, 230, COLOR_WHITE);   // 反对角线
    vTaskDelay(2000 / portTICK_PERIOD_MS);
    
    // 测试6: 绘制矩形边框和填充矩形
    ESP_LOGI(TAG, "Test 6: RECTANGLES");
    st7789_fill_rect(0, 0, SCREEN_WIDTH - 1, SCREEN_HEIGHT - 1, COLOR_BLACK);
    st7789_draw_rect(20, 20, 100, 100, COLOR_RED);      // 红色矩形边框
    st7789_fill_rect(120, 20, 200, 100, COLOR_GREEN);   // 绿色填充矩形
    st7789_draw_rect(20, 120, 100, 200, COLOR_BLUE);    // 蓝色矩形边框
    st7789_fill_rect(120, 120, 200, 200, COLOR_YELLOW); // 黄色填充矩形
    vTaskDelay(2000 / portTICK_PERIOD_MS);
    
    // 测试7: 绘制圆形和填充圆形
    ESP_LOGI(TAG, "Test 7: CIRCLES");
    st7789_fill_rect(0, 0, SCREEN_WIDTH - 1, SCREEN_HEIGHT - 1, COLOR_BLACK);
    st7789_draw_circle(60, 80, 40, COLOR_RED);          // 红色圆形边框
    st7789_fill_circle(180, 80, 40, COLOR_GREEN);       // 绿色填充圆形
    st7789_draw_circle(60, 180, 30, COLOR_BLUE);        // 蓝色圆形边框
    st7789_fill_circle(180, 180, 30, COLOR_YELLOW);     // 黄色填充圆形
    vTaskDelay(2000 / portTICK_PERIOD_MS);
    
    // 测试8: 绘制三角形
    ESP_LOGI(TAG, "Test 8: TRIANGLES");
    st7789_fill_rect(0, 0, SCREEN_WIDTH - 1, SCREEN_HEIGHT - 1, COLOR_BLACK);
    st7789_draw_triangle(120, 30, 50, 150, 190, 150, COLOR_RED);    // 红色三角形
    st7789_draw_triangle(120, 180, 60, 220, 180, 220, COLOR_GREEN); // 绿色三角形
    vTaskDelay(2000 / portTICK_PERIOD_MS);
    
    // 测试9: 综合图形测试
    ESP_LOGI(TAG, "Test 9: COMBINED");
    st7789_fill_rect(0, 0, SCREEN_WIDTH - 1, SCREEN_HEIGHT - 1, COLOR_BLACK);
    st7789_draw_string(50, 20, "GRAPHICS TEST", COLOR_WHITE, COLOR_BLACK);
    st7789_draw_rect(10, 40, 230, 230, COLOR_WHITE);    // 外框
    st7789_draw_circle(120, 120, 50, COLOR_YELLOW);     // 中心圆
    st7789_fill_circle(120, 120, 20, COLOR_ORANGE);     // 中心小圆
    st7789_draw_line(120, 70, 120, 170, COLOR_RED);     // 垂直线
    st7789_draw_line(70, 120, 170, 120, COLOR_BLUE);    // 水平线
    st7789_draw_triangle(120, 45, 100, 70, 140, 70, COLOR_GREEN); // 顶部三角形
    vTaskDelay(2000 / portTICK_PERIOD_MS);
    
    ESP_LOGI(TAG, "Display test completed!");
    
    while (1) {
        vTaskDelay(1000 / portTICK_PERIOD_MS);
    }
#else
    /* 初始化硬件 */
    adc_init();
    digital_key_init();
    led_init();

    /* 初始化显示屏 */
    st7789_init();

    /* 初始化游戏 */
    game_init();

    /* 创建按键处理任务 */
    xTaskCreate(key_task, "key_task", 2048, NULL, 5, NULL);

    /* 创建游戏任务 */
    xTaskCreate(game_task, "game_task", 2048, NULL, 5, NULL);

    ESP_LOGI(TAG, "Tasks created, game started");
#endif
}