/**
 * @file snake_game.c
 * @brief ESP32-C3 贪吃蛇游戏实现
 * @author Generated by AI
 * @date 2026-05-29
 */
#include <stdbool.h>
#include <stdio.h>
#include "snake_game.h"
#include "st7789.h"
#include "esp_log.h"
#include "esp_random.h"

static const char *TAG = "SnakeGame";

/* 游戏数据 */
static GameData_t game_data;

/**
 * @brief 生成随机食物位置
 */
static void spawn_food(void)
{
    // 确保食物不会生成在蛇身上
    int attempts = 0;
    do {
        game_data.food.x = esp_random() % GRID_COLS;
        game_data.food.y = esp_random() % GRID_ROWS;
        attempts++;
    } while (attempts < 100);
}

/**
 * @brief 检查点是否在蛇身上
 */
static bool is_on_snake(int16_t x, int16_t y)
{
    for (uint16_t i = 0; i < game_data.snake.length; i++) {
        if (game_data.snake.body[i].x == x && game_data.snake.body[i].y == y) {
            return true;
        }
    }
    return false;
}

/**
 * @brief 重新生成食物直到不在蛇身上
 */
static void respawn_food(void)
{
    do {
        spawn_food();
    } while (is_on_snake(game_data.food.x, game_data.food.y));
}

/**
 * @brief 初始化贪吃蛇
 */
static void snake_init(void)
{
    game_data.snake.length = 3;
    game_data.snake.dir = DIR_RIGHT;

    // 初始化蛇的位置在屏幕中心偏左
    game_data.snake.body[0].x = GRID_COLS / 2 - 1;
    game_data.snake.body[0].y = GRID_ROWS / 2;
    game_data.snake.body[1].x = GRID_COLS / 2 - 2;
    game_data.snake.body[1].y = GRID_ROWS / 2;
    game_data.snake.body[2].x = GRID_COLS / 2 - 3;
    game_data.snake.body[2].y = GRID_ROWS / 2;
}

/**
 * @brief 移动蛇
 */
static bool move_snake(void)
{
    // 计算新头部位置
    Point_t new_head = game_data.snake.body[0];

    switch (game_data.snake.dir) {
        case DIR_UP:
            new_head.y--;
            break;
        case DIR_DOWN:
            new_head.y++;
            break;
        case DIR_LEFT:
            new_head.x--;
            break;
        case DIR_RIGHT:
            new_head.x++;
            break;
        default:
            return false;
    }

    // 检查边界碰撞
    if (new_head.x < 0 || new_head.x >= GRID_COLS ||
        new_head.y < 0 || new_head.y >= GRID_ROWS) {
        return false;
    }

    // 检查自身碰撞
    if (is_on_snake(new_head.x, new_head.y)) {
        return false;
    }

    // 移动蛇身体
    for (int16_t i = game_data.snake.length - 1; i > 0; i--) {
        game_data.snake.body[i] = game_data.snake.body[i - 1];
    }
    game_data.snake.body[0] = new_head;

    // 检查是否吃到食物
    if (new_head.x == game_data.food.x && new_head.y == game_data.food.y) {
        // 增加蛇长度
        game_data.snake.length++;
        game_data.score += 10;

        // 重新生成食物
        respawn_food();
    }

    return true;
}

/**
 * @brief 绘制蛇
 */
static void draw_snake(void)
{
    for (uint16_t i = 0; i < game_data.snake.length; i++) {
        uint16_t x = game_data.snake.body[i].x * GRID_SIZE;
        uint16_t y = game_data.snake.body[i].y * GRID_SIZE;

        if (i == 0) {
            // 蛇头用橙色
            st7789_fill_rect(x, y, x + GRID_SIZE - 1, y + GRID_SIZE - 1, COLOR_ORANGE);
        } else {
            // 蛇身用绿色
            st7789_fill_rect(x, y, x + GRID_SIZE - 1, y + GRID_SIZE - 1, COLOR_GREEN);
        }
    }
}

/**
 * @brief 绘制食物
 */
static void draw_food(void)
{
    uint16_t x = game_data.food.x * GRID_SIZE;
    uint16_t y = game_data.food.y * GRID_SIZE;
    st7789_fill_rect(x, y, x + GRID_SIZE - 1, y + GRID_SIZE - 1, COLOR_RED);
}

/**
 * @brief 绘制游戏场景
 */
static void draw_game(void)
{
    // 清屏
    st7789_clear(COLOR_BLACK);

    // 绘制网格线
    for (int i = 0; i <= GRID_COLS; i++) {
        st7789_fill_rect(i * GRID_SIZE, 0, i * GRID_SIZE, SCREEN_HEIGHT - 1, 0x1800);
    }
    for (int i = 0; i <= GRID_ROWS; i++) {
        st7789_fill_rect(0, i * GRID_SIZE, SCREEN_WIDTH - 1, i * GRID_SIZE, 0x1800);
    }

    // 绘制食物和蛇
    draw_food();
    draw_snake();
}

/**
 * @brief 显示游戏结束画面
 */
static void draw_game_over(void)
{
    st7789_clear(COLOR_BLACK);

    // 显示游戏结束文字
    st7789_draw_string(60, 80, "GAME OVER", COLOR_RED, COLOR_BLACK);

    // 显示分数
    char score_str[20];
    sprintf(score_str, "SCORE: %lu", game_data.score);
    st7789_draw_string(55, 100, score_str, COLOR_YELLOW, COLOR_BLACK);

    // 显示提示
    st7789_draw_string(40, 140, "Press OK to restart", COLOR_WHITE, COLOR_BLACK);
}

/**
 * @brief 显示开始画面
 */
static void draw_start_screen(void)
{
    st7789_clear(COLOR_BLACK);

    // 显示标题
    st7789_draw_string(70, 60, "SNAKE", COLOR_GREEN, COLOR_BLACK);

    // 显示提示
    st7789_draw_string(40, 100, "Press OK to start", COLOR_WHITE, COLOR_BLACK);
    st7789_draw_string(35, 120, "ADC keys: UP/DOWN", COLOR_WHITE, COLOR_BLACK);
    st7789_draw_string(35, 140, "LEFT/RIGHT", COLOR_WHITE, COLOR_BLACK);
    st7789_draw_string(45, 160, "IO9: Exit", COLOR_WHITE, COLOR_BLACK);
}

/**
 * @brief 显示暂停画面
 */
static void draw_paused(void)
{
    // 先绘制游戏画面
    draw_game();

    // 显示暂停遮罩
    st7789_fill_rect(0, 100, SCREEN_WIDTH - 1, 140, 0x8000);

    // 显示暂停文字
    st7789_draw_string(70, 105, "PAUSED", COLOR_YELLOW, COLOR_BLACK);
    st7789_draw_string(50, 125, "Press OK to continue", COLOR_WHITE, COLOR_BLACK);
}

void game_init(void)
{
    ESP_LOGI(TAG, "Initializing game...");

    game_data.state = GAME_IDLE;
    game_data.score = 0;

    snake_init();
    spawn_food();

    // 绘制开始画面
    draw_start_screen();

    ESP_LOGI(TAG, "Game initialized");
}

void game_start(void)
{
    ESP_LOGI(TAG, "Starting game");

    game_data.state = GAME_PLAYING;
    game_data.score = 0;

    snake_init();
    spawn_food();

    draw_game();
}

void game_toggle_pause(void)
{
    if (game_data.state == GAME_PLAYING) {
        game_data.state = GAME_PAUSED;
        draw_paused();
        ESP_LOGI(TAG, "Game paused");
    } else if (game_data.state == GAME_PAUSED) {
        game_data.state = GAME_PLAYING;
        draw_game();
        ESP_LOGI(TAG, "Game resumed");
    }
}

void game_reset(void)
{
    ESP_LOGI(TAG, "Resetting game");

    game_data.state = GAME_IDLE;
    game_data.score = 0;

    snake_init();
    spawn_food();

    draw_start_screen();
}

void game_update(void)
{
    if (game_data.state != GAME_PLAYING) {
        return;
    }

    if (!move_snake()) {
        game_data.state = GAME_OVER;
        draw_game_over();
        ESP_LOGI(TAG, "Game over! Score: %lu", game_data.score);
        return;
    }

    draw_game();
}

void game_change_dir(Direction_t dir)
{
    if (game_data.state != GAME_PLAYING) {
        return;
    }

    // 防止反向移动
    if ((game_data.snake.dir == DIR_UP && dir == DIR_DOWN) ||
        (game_data.snake.dir == DIR_DOWN && dir == DIR_UP) ||
        (game_data.snake.dir == DIR_LEFT && dir == DIR_RIGHT) ||
        (game_data.snake.dir == DIR_RIGHT && dir == DIR_LEFT)) {
        return;
    }

    game_data.snake.dir = dir;
    ESP_LOGI(TAG, "Direction changed to %d", dir);
}

GameState_t game_get_state(void)
{
    return game_data.state;
}

uint32_t game_get_score(void)
{
    return game_data.score;
}