/**
 * @file snake_game.h
 * @brief ESP32-C3 贪吃蛇游戏头文件
 * @author Generated by AI
 * @date 2026-05-29
 */

#ifndef SNAKE_GAME_H
#define SNAKE_GAME_H

#include <stdint.h>
#include "st7789.h"

/* 游戏配置 */
#define GRID_SIZE       12          // 每个格子大小(像素)
#define GRID_COLS       (SCREEN_WIDTH / GRID_SIZE)   // 列数
#define GRID_ROWS       (SCREEN_HEIGHT / GRID_SIZE)  // 行数

/* 按键ADC阈值配置 */
#define ADC_THRESHOLD_DOWN      800     // 下
#define ADC_THRESHOLD_LEFT      1600    // 左
#define ADC_THRESHOLD_RIGHT     2400    // 右
#define ADC_THRESHOLD_UP        3100    // 上
#define ADC_THRESHOLD_CONFIRM   3900    // 确认
#define ADC_THRESHOLD_MAX       4095    // 最大值

/* 方向定义 */
typedef enum {
    DIR_UP = 0,
    DIR_DOWN,
    DIR_LEFT,
    DIR_RIGHT,
    DIR_NONE
} Direction_t;

/* 游戏状态 */
typedef enum {
    GAME_IDLE = 0,      // 空闲状态
    GAME_PLAYING,       // 游戏中
    GAME_PAUSED,        // 暂停
    GAME_OVER           // 游戏结束
} GameState_t;

/* 坐标点 */
typedef struct {
    int16_t x;
    int16_t y;
} Point_t;

/* 贪吃蛇结构体 */
typedef struct {
    Point_t body[GRID_COLS * GRID_ROWS];  // 蛇身体
    uint16_t length;                       // 蛇长度
    Direction_t dir;                       // 当前方向
} Snake_t;

/* 游戏数据 */
typedef struct {
    Snake_t snake;
    Point_t food;
    uint32_t score;
    GameState_t state;
} GameData_t;

/* 函数声明 */

/**
 * @brief 初始化游戏
 */
void game_init(void);

/**
 * @brief 开始游戏
 */
void game_start(void);

/**
 * @brief 暂停/继续游戏
 */
void game_toggle_pause(void);

/**
 * @brief 重置游戏
 */
void game_reset(void);

/**
 * @brief 更新游戏状态
 */
void game_update(void);

/**
 * @brief 改变方向
 * @param dir 新方向
 */
void game_change_dir(Direction_t dir);

/**
 * @brief 获取游戏状态
 * @return 游戏状态
 */
GameState_t game_get_state(void);

/**
 * @brief 获取分数
 * @return 当前分数
 */
uint32_t game_get_score(void);

#endif /* SNAKE_GAME_H */