/**
 * @file st7789.h
 * @brief ST7789 SPI显示屏驱动头文件
 * @author Generated by AI
 * @date 2026-05-29
 */

#ifndef ST7789_H
#define ST7789_H

#include <stddef.h>
#include <stdint.h>

/* 屏幕尺寸定义 */
#define SCREEN_WIDTH    240
#define SCREEN_HEIGHT   240

/* 颜色定义 (BGR565格式，适配ST7789) */
#define COLOR_BLACK     0x0000
#define COLOR_WHITE     0xFFFF
#define COLOR_RED       0x001F      // B=0, G=0, R=31
#define COLOR_GREEN     0x07E0      // B=0, G=31, R=0
#define COLOR_BLUE      0xF800      // B=31, G=0, R=0
#define COLOR_YELLOW    0x07FF      // B=0, G=31, R=31
#define COLOR_ORANGE    0x07DF      // B=0, G=30, R=31

/* ST7789 命令定义 */
#define ST7789_NOP         0x00    // 空操作
#define ST7789_SWRESET     0x01    // 软件复位
#define ST7789_RDDID       0x04    // 读取ID
#define ST7789_RDDST       0x09    // 读取显示状态
#define ST7789_RDDPM       0x0A    // 读取电源模式
#define ST7789_RDD_MADCTL  0x0B    // 读取MADCTL
#define ST7789_RDD_COLMOD  0x0C    // 读取颜色模式
#define ST7789_RDDIM       0x0D    // 读取显示图像模式
#define ST7789_RDDSM       0x0E    // 读取显示信号模式
#define ST7789_RDDSDR      0x0F    // 读取显示自我诊断结果

#define ST7789_SLPIN       0x10    // 睡眠进入
#define ST7789_SLPOUT      0x11    // 睡眠退出
#define ST7789_PTLON       0x12    // 部分显示模式进入
#define ST7789_NORON       0x13    // 正常显示模式恢复

#define ST7789_INVOFF      0x20    // 显示反转关闭
#define ST7789_INVON       0x21    // 显示反转开启
#define ST7789_GAMSET      0x26    // 伽马设置
#define ST7789_DISPOFF     0x28    // 显示关闭
#define ST7789_DISPON      0x29    // 显示开启

#define ST7789_CASET       0x2A    // 列地址设置
#define ST7789_RASET       0x2B    // 行地址设置
#define ST7789_RAMWR       0x2C    // 内存写入
#define ST7789_RAMRD       0x2E    // 内存读取

#define ST7789_PTLAR       0x30    // 部分区域
#define ST7789_VSCRDEF     0x33    // 垂直滚动定义
#define ST7789_TEOFF       0x34    // 撕裂效果线关闭
#define ST7789_TEON        0x35    // 撕裂效果线开启
#define ST7789_MADCTL      0x36    // 内存访问控制
#define ST7789_VSCRSADD    0x37    // 垂直滚动起始地址
#define ST7789_IDMOFF      0x38    // 空闲模式关闭
#define ST7789_IDMON       0x39    // 空闲模式开启
#define ST7789_COLMOD      0x3A    // 颜色模式

#define ST7789_RDID1       0xDA    // 读取ID1
#define ST7789_RDID2       0xDB    // 读取ID2
#define ST7789_RDID3       0xDC    // 读取ID3

#define ST7789_RAMCTRL     0xB0    // 内存控制
#define ST7789_RGBCTRL     0xB1    // RGB控制
#define ST7789_PORCTRL     0xB2    // 端口控制
#define ST7789_FRCTRL1     0xB3    // 帧速率控制(正常模式/全屏)
#define ST7789_PARCTRL     0xB5    // 部分区域控制
#define ST7789_GCTRL       0xB7    // 网关控制
#define ST7789_DGMEN       0xB8    // 显示伽马启用
#define ST7789_GTADJ       0xB9    // 伽马调整
#define ST7789_VCOMS       0xBB    // VCOM设置

#define ST7789_LCMCTRL     0xC0    // LCM控制
#define ST7789_IDSET       0xC1    // ID设置
#define ST7789_VDVVRHEN    0xC2    // VDV和VRC启用
#define ST7789_VRHS        0xC3    // VRHS设置
#define ST7789_VDVSET      0xC4    // VDV设置
#define ST7789_VCMOFSET    0xC5    // VCOM偏移设置
#define ST7789_FRCTR2      0xC6    // 帧速率控制(Idle模式)
#define ST7789_CABCCTRL    0xC7    // CABC控制

#define ST7789_REGSEL1     0xD0    // 寄存器选择1
#define ST7789_REGSEL2     0xD1    // 寄存器选择2
#define ST7789_RDID4       0xD3    // 读取ID4

#define ST7789_PWCTRL1     0xD6    // 电源控制1
#define ST7789_VAPVANEN    0xD7    // VAP/VAN信号启用

#define ST7789_PGAMCTRL    0xE0    // 正伽马校正
#define ST7789_NGAMCTRL    0xE1    // 负伽马校正

#define ST7789_DLPOFFSAVE  0xE2    // 深睡眠模式保存
#define ST7789_PWCTR6      0xFC    // 电源控制6

/* 颜色格式 */
#define COLOR_MODE_65K     0x50
#define COLOR_MODE_262K    0x60
#define COLOR_MODE_12BIT   0x03
#define COLOR_MODE_16BIT   0x05
#define COLOR_MODE_18BIT   0x06
#define COLOR_MODE_16M     0x07

/* 函数声明 */

/**
 * @brief 初始化ST7789显示屏
 */
void st7789_init(void);

/**
 * @brief 发送命令
 * @param cmd 命令字节
 */
void st7789_send_cmd(uint8_t cmd);

/**
 * @brief 发送数据
 * @param data 数据字节
 */
void st7789_send_data(uint8_t data);

/**
 * @brief 发送多字节数据
 * @param data 数据指针
 * @param len 数据长度
 */
void st7789_send_data_bytes(const uint8_t *data, size_t len);

/**
 * @brief 设置显示区域
 * @param x1 起始X坐标
 * @param y1 起始Y坐标
 * @param x2 结束X坐标
 * @param y2 结束Y坐标
 */
void st7789_set_window(uint16_t x1, uint16_t y1, uint16_t x2, uint16_t y2);

/**
 * @brief 填充矩形区域
 * @param x1 起始X坐标
 * @param y1 起始Y坐标
 * @param x2 结束X坐标
 * @param y2 结束Y坐标
 * @param color 颜色
 */
void st7789_fill_rect(uint16_t x1, uint16_t y1, uint16_t x2, uint16_t y2, uint16_t color);

/**
 * @brief 绘制像素点
 * @param x X坐标
 * @param y Y坐标
 * @param color 颜色
 */
void st7789_draw_pixel(uint16_t x, uint16_t y, uint16_t color);

/**
 * @brief 清屏
 * @param color 清屏颜色
 */
void st7789_clear(uint16_t color);

/**
 * @brief 绘制字符
 * @param x X坐标
 * @param y Y坐标
 * @param c 字符
 * @param color 字符颜色
 * @param bg_color 背景颜色
 */
void st7789_draw_char(uint16_t x, uint16_t y, char c, uint16_t color, uint16_t bg_color);

/**
 * @brief 绘制字符串
 * @param x X坐标
 * @param y Y坐标
 * @param str 字符串指针
 * @param color 字符颜色
 * @param bg_color 背景颜色
 */
void st7789_draw_string(uint16_t x, uint16_t y, const char *str, uint16_t color, uint16_t bg_color);

/**
 * @brief 使用Bresenham算法绘制直线
 * @param x1 起始X坐标
 * @param y1 起始Y坐标
 * @param x2 结束X坐标
 * @param y2 结束Y坐标
 * @param color 颜色
 */
void st7789_draw_line(uint16_t x1, uint16_t y1, uint16_t x2, uint16_t y2, uint16_t color);

/**
 * @brief 绘制矩形边框
 * @param x1 左上角X坐标
 * @param y1 左上角Y坐标
 * @param x2 右下角X坐标
 * @param y2 右下角Y坐标
 * @param color 颜色
 */
void st7789_draw_rect(uint16_t x1, uint16_t y1, uint16_t x2, uint16_t y2, uint16_t color);

/**
 * @brief 使用Bresenham算法绘制圆
 * @param x0 圆心X坐标
 * @param y0 圆心Y坐标
 * @param r 半径
 * @param color 颜色
 */
void st7789_draw_circle(uint16_t x0, uint16_t y0, uint16_t r, uint16_t color);

/**
 * @brief 填充圆
 * @param x0 圆心X坐标
 * @param y0 圆心Y坐标
 * @param r 半径
 * @param color 颜色
 */
void st7789_fill_circle(uint16_t x0, uint16_t y0, uint16_t r, uint16_t color);

/**
 * @brief 绘制三角形
 * @param x1 顶点1 X坐标
 * @param y1 顶点1 Y坐标
 * @param x2 顶点2 X坐标
 * @param y2 顶点2 Y坐标
 * @param x3 顶点3 X坐标
 * @param y3 顶点3 Y坐标
 * @param color 颜色
 */
void st7789_draw_triangle(uint16_t x1, uint16_t y1, uint16_t x2, uint16_t y2, uint16_t x3, uint16_t y3, uint16_t color);

#endif /* ST7789_H */